include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - avoid_print
    - avoid_unnecessary_containers
    - prefer_single_quotes
    - always_declare_return_types
    - require_trailing_commas

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - 'build/**'
  errors:
    invalid_annotation_target: ignore
    non_abstract_class_inherits_abstract_member: ignore
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
