version: '3.8'

services:
  chat-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    container_name: chat-app
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
