name: chat_app
description: A cross-platform AI chat application similar to Cherry Studio
publish_to: 'none'

version: 1.4.0+5

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  
  # Navigation
  go_router: ^16.2.5
  
  # Network
  dio: ^5.7.0
  retrofit: ^4.1.1
  pretty_dio_logger: ^1.3.3
  
  # Permissions
  permission_handler: ^12.0.1
  connectivity_plus: ^7.0.0
  
  # Local Storage
  hive: ^2.2.0
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  
  # Code Generation
  json_annotation: ^4.9.0
  
  # UI Components
  markdown_widget: ^2.3.0
  flutter_highlight: ^0.7.0
  flutter_svg: ^2.0.10
  markdown: ^7.3.0
  flutter_markdown: ^0.7.7+1
  
  # Platform Specific
  window_manager: ^0.5.1
  tray_manager: ^0.5.0
  file_picker: ^10.3.3
  share_plus: ^12.0.0
  url_launcher: ^6.3.0
  
  # Utilities
  intl: ^0.20.2
  uuid: ^4.3.4
  equatable: ^2.0.6
  logger: ^2.4.0
  pdf: ^3.10.0
  printing: ^5.10.0
  flutter_math_fork: ^0.7.0
  riverpod: ^3.0.3
  expressions: ^0.2.5
  path: ^1.9.1
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.7.1
  json_serializable: ^6.11.1
  riverpod_generator: ^3.0.3
  retrofit_generator: ^10.0.0
  
  # Testing
  mockito: ^5.5.0
  http_mock_adapter: ^0.6.1
  
  # Linting
  flutter_lints: ^6.0.0
  
  # App Icon Generation
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/backgrounds/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#6366F1"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#6366F1"
    theme_color: "#6366F1"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"
