name: chat_app
description: A cross-platform AI chat application similar to Cherry Studio
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  
  # Navigation
  go_router: ^16.2.4
  
  # Network
  dio: ^5.4.0
  retrofit: ^4.0.3
  pretty_dio_logger: ^1.3.1
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^10.0.0-beta.4
  path_provider: ^2.1.2
  
  # Code Generation
  freezed_annotation: ^3.1.0
  json_annotation: ^4.8.1
  
  # UI Components
  flutter_markdown: ^0.7.7+1
  flutter_highlight: ^0.7.0
  flutter_svg: ^2.0.9
  markdown: ^7.2.0
  
  # Platform Specific
  window_manager: ^0.5.1
  tray_manager: ^0.5.1
  file_picker: ^10.3.3
  share_plus: ^12.0.0
  url_launcher: ^6.2.3
  
  # Utilities
  intl: ^0.20.2
  uuid: ^4.3.3
  equatable: ^2.0.5
  logger: ^2.0.2+1
  pdf: ^3.11.3
  printing: ^5.14.2
  flutter_math_fork: ^0.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.13
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  riverpod_generator: ^3.0.3
  retrofit_generator: ^10.0.0
  
  # Testing
  mockito: ^5.4.4
  
  # Linting
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
